# spring:
#   profiles: default
# eureka:
#   instance:
#     # enable to register multiple app instances with a random server port
#     instance-id: ${spring.application.name}:${random.uuid}

# ---
# spring:
#   profiles: docker
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://discovery-server:8761/eureka/

---
spring:
  profiles: cloud
  boot:
    admin:
      discovery:
        enabled: true
  # zipkin:
  #   baseUrl: http://tracing-server:9411
eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://bens-discovery-server.apps.tas.tanzu-demo.net/eureka
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    healthCheckUrl: http://${vcap.application.uris[0]}/actuator/health
    metadata-map:
      management.port: 80
      applicationId: ${vcap.application.application_id}
      instanceId: ${vcap.application.instance_index}