# spring:
#   profiles: default
# eureka:
#   instance:
#     # enable to register multiple app instances with a random server port
#     instance-id: ${spring.application.name}:${random.uuid}

# ---
# spring:
#   profiles: docker
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://discovery-server:8761/eureka/

---
spring:
  profiles: tas
  boot:
    admin:
      discovery:
        enabled: true
eureka:
  client:
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 10