# Settings for the ADMIN server.

spring:
  boot:
    admin:
      discovery:
        enabled: true
eureka:
  client:
    registryFetchIntervalSeconds: 30
  instance:
    leaseRenewalIntervalInSeconds: 30