spring:
  profiles: default


---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

---
spring:
  profiles: cloud
  # zipkin:
  #   baseUrl: http://tracing-server:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://bens-discovery-server.apps.tas.workload.tkglab.tanzu-demo.net/eureka