spring:
  zipkin:
    enabled: true
    discoveryClientEnabled: false
    messageTimeout: 10
    baseUrl: http://tracing-server-service.default.svc.cluster.local:9411
    sender:
      type: web
eureka:
  instance:
    preferIpAddress: true
