# Settings given to ALL applications started under the KUBERNETES profile

# Register using IP Address
eureka:
  instance:
    preferIpAddress: true

#spring:
#  zipkin:
#    discoveryClientEnabled: false
#    messageTimeout: 10
#    sender:
#      type: web
