# Settings for all applications started under the TAS profile.
spring:
  zipkin:
    discoveryClientEnabled: false
    messageTimeout: 10
    sender:
      type: web
eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    healthCheckUrl: http://${vcap.application.uris[0]}/actuator/health
    metadata-map:
      management.port: 80
      applicationId: ${vcap.application.application_id}
      instanceId: ${vcap.application.instance_index}
