---
spring:
  profiles: tas
  zipkin:
    enabled: true
    discoveryClientEnabled: false
    sender.type: web
    baseUrl: http://bens-zipkin-server.apps.tas.tanzu-demo.net:80
eureka:
  client:
    serviceUrl:
      defaultZone: http://bens-discovery-server.apps.tas.tanzu-demo.net/eureka
    healthcheck:
      enabled: true
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    healthCheckUrl: http://${vcap.application.uris[0]}/actuator/health
    metadata-map:
      management.port: 80
      applicationId: ${vcap.application.application_id}
      instanceId: ${vcap.application.instance_index}
logging:
  level:
    root: INFO
#    org.springframework.cloud: INFO
    org.springframework.cloud.sleuth.zipkin2: DEBUG
    org.springframework.samples.petclinic: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
#    com.netflix: INFO
