# COMMON APPLICATION PROPERTIES given to ALL applications

# Server specifics
server:
  port: ${PORT} # Use the PORT Given in the PORT environment variable
  shutdown: graceful # The stop processing uses a timeout which provides a grace period during which existing requests will be allowed to complete but no new requests will be permitted

# Discovery endpoint
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URI} # Use the DISCOVERY_SERVER_URI environment variable as the endpoint (e.g. http://localhost:8761/eureka)
    healthcheck:
      enabled: false
  instance:
    preferIpAddress: true # Included here in the main application.yml as a workaround for https://github.com/spring-cloud/spring-cloud-config/issues/1783     

# Spring Boot settings

spring:
  zipkin:
    enabled: true
    discovery-client-enabled: false
    baseUrl: ${TRACING_SERVER_URI} # Use the TRACING_SERVER_URI environment variable as the endpoint (e.g. http://localhost:9411)
  datasource:
    schema: classpath*:db/hsqldb/schema.sql
    data: classpath*:db/hsqldb/data.sql
  cloud:
    refresh:
      refreshable: false # Temporary hack required by the Spring Boot 2 / Spring Cloud Finchley branch. Waiting issue https://github.com/spring-projects/spring-boot/issues/13042
#    config:
#      allowOverride: true # Allow the microservices to override the remote properties with their own System properties or config file
#      overrideNone: true # Override configuration with any local property source
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

# Actuator settings
management:
  port: ${PORT} # Set the actuator PORT to match the application's PORT as set in the ENV
  security:
    enabled: false # Spring Boot 1.5 makes actuator secure by default
  endpoints:
    web:
      exposure.include: '*' # Enable all Actuators and not only the two available by default /health and /info starting Spring Boot 2.0
  endpoint:
    health:
      show-details: ALWAYS # Show detailed health
    metrics:
      enabled: true
    prometheus:
      enabled: true

# Logging levels
#logging:
#  level.root: INFO


