---
spring:
  profiles: tas
  zipkin:
    enabled: true
    discoveryClientEnabled: false
    messageTimeout: 10
    baseUrl: http://bens-zipkin-server.apps.tas.tanzu-demo.net:80
    sender:
      type: web
eureka:
  client:
    serviceUrl:
      defaultZone: http://bens-discovery-server.apps.tas.tanzu-demo.net/eureka
    healthcheck:
      enabled: true
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    healthCheckUrl: http://${vcap.application.uris[0]}/actuator/health
    metadata-map:
      management.port: 80
      applicationId: ${vcap.application.application_id}
      instanceId: ${vcap.application.instance_index}
logging:
  level:
    root: INFO
#    org.springframework.cloud: INFO
#    org.springframework.cloud.sleuth.instrument.web: DEBUG
