message: haloha

spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

---
spring:
  profiles: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: http://bens-discovery-server.apps.tas.tanzu-demo.net/eureka
    healthcheck:
      enabled: true
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    metadataMap:
      management.port: 80
message: ola!