# Settings for the VETS-SERVICE application.
vets:
  cache:
    ttl: 60
    heap-size: 100
spring:
  profiles:
    active: production
  cache:
    cache-names: vets
eureka:
  instance:
    hostname: ${VETS_SERVICE_SERVICE_PORT_8083_TCP_ADDR}
    nonSecurePort: 8083
